dbt_monzo_analytics:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: # INSERT PROJECT ID HERE
      dataset: # INSERT DATASET NAME HERE
      threads: 4
      keyfile: ./creds/*.json # INSERT SERVICE ACCOUNT KEY JSON HERE
      location: EU
  target: dev